default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: agile-fuel_development

test:
  <<: *default
  database: agile-fuel_test

production:
  <<: *default
  database: agile-fuel_production
  username: agile-fuel
  password: <%= ENV['AGILE-FUEL_DATABASE_PASSWORD'] %>
